// Highlights a color word (e.g. "green", "red") in that actual color, like a
// marker highlight. Used throughout the course wherever a trace/cell color is
// called out. Generated by the docx converter.

type Swatch = { bg: string; fg: string; border?: string };

const PALETTE: Record<string, Swatch> = {
  red: { bg: "#DC2626", fg: "#FFFFFF" },
  orange: { bg: "#EA580C", fg: "#FFFFFF" },
  yellow: { bg: "#FDE047", fg: "#1A1A1A" },
  green: { bg: "#16A34A", fg: "#FFFFFF" },
  blue: { bg: "#2563EB", fg: "#FFFFFF" },
  purple: { bg: "#7C3AED", fg: "#FFFFFF" },
  violet: { bg: "#7C3AED", fg: "#FFFFFF" },
  indigo: { bg: "#4F46E5", fg: "#FFFFFF" },
  pink: { bg: "#EC4899", fg: "#FFFFFF" },
  magenta: { bg: "#D946EF", fg: "#FFFFFF" },
  cyan: { bg: "#06B6D4", fg: "#1A1A1A" },
  aqua: { bg: "#06B6D4", fg: "#1A1A1A" },
  teal: { bg: "#0D9488", fg: "#FFFFFF" },
  brown: { bg: "#92400E", fg: "#FFFFFF" },
  tan: { bg: "#D2B48C", fg: "#1A1A1A" },
  beige: { bg: "#E7DCC3", fg: "#1A1A1A", border: "#CBB994" },
  gray: { bg: "#9CA3AF", fg: "#1A1A1A" },
  grey: { bg: "#9CA3AF", fg: "#1A1A1A" },
  silver: { bg: "#C0C0C0", fg: "#1A1A1A", border: "#A3A3A3" },
  black: { bg: "#1A1A1A", fg: "#FFFFFF" },
  white: { bg: "#FFFFFF", fg: "#1A1A1A", border: "#CBD5E1" },
  gold: { bg: "#D4AF37", fg: "#1A1A1A" },
  lime: { bg: "#84CC16", fg: "#1A1A1A" },
  navy: { bg: "#1E3A8A", fg: "#FFFFFF" },
  maroon: { bg: "#7F1D1D", fg: "#FFFFFF" },
  olive: { bg: "#4D7C0F", fg: "#FFFFFF" },
};

export default function ColorWord({ c, children }: { c: string; children: React.ReactNode }) {
  const swatch = PALETTE[c.toLowerCase()] || PALETTE.gray;
  return (
    <span
      className="rounded px-1 font-semibold"
      style={{
        backgroundColor: swatch.bg,
        color: swatch.fg,
        boxShadow: swatch.border ? `inset 0 0 0 1px ${swatch.border}` : undefined,
      }}
    >
      {children}
    </span>
  );
}
